### ISSUE TITLE
Spritesets could be simplified

### ISSUE THREAD

**Issue by wensimehrp** [OpenTTD-China-Set/China-Set-Trains#28]
See https://github.com/OpenTTD-China-Set/China-Set-MTR-Addon/issues/1
I don't really understand why even new codes contian the same spriteset() + alternative_sprites() structure. In theory when using nml 0.7.5 this part could be simplified.

**Comment by jfkuayue** [comment]
Is this solved now?

**Comment by wensimehrp** [comment]
solved via #33
